#!/bin/bash

set -eu

cd $(dirname "$BASH_SOURCE")/..

# for some reason combining both options does not seem to work
PIPENV_VENV_IN_PROJECT=1 pipenv sync --dev
PIPENV_VENV_IN_PROJECT=1 pipenv sync --categories=dev-local